### ISSUE TITLE
Questions about program

### ISSUE THREAD

**Issue by Actpohomoc** [pradyumnac/AliexpressOrders#1]
Hi! Thank you to share your nice work. I would like to understand how does it work.
I want to use this feature to load all info about ali orders to my 1C:Money program. 
[http://v8.1c.ru/money/](http://v8.1c.ru/money/)
[http://online.1c.ru/catalog/programs/program/14229054/](http://online.1c.ru/catalog/programs/program/14229054/)
And that why I have some questions. 
1. Can you pls tell me abou sheets.cpython-35.pyc. What is this py byte code file with?
2. As I understand it is possible to generate the json file with all info about orders?

**Comment by pradyumnac** [comment]
1. The file that you see in __pycache__ is internally generated by python parsing sheets.py. Did not realize it got checked into repo..
2. 
** orders = get_open_orders(os.environ['AE_username'],os.environ['AE_passwd'],"Chrome","D:\Projects\projects\cams\chromedriver.exe")
This line gets you the orders object. Follow this up with a json.dumps(orders) to get a json string
